kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  namespace: default
  name: data-pvc
  labels:
    app: postgres
spec:
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
