version: "2"

formatters:
  enable:
    - gofmt
    - goimports

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gocritic
    - misspell
    - revive
    - gocyclo
    - goconst
  settings:
    errcheck:
      check-type-assertions: true
      check-blank: true
    goconst:
      min-len: 2
      min-occurrences: 2
    gocritic:
      enabled-tags:
        - diagnostic
        - experimental
        - opinionated
        - performance
        - style
      disabled-checks:
        - dupImport
        - ifElseChain
        - octalLiteral
        - whyNoLint
        - wrapperFunc
    govet:
      check-shadowing: true
    gocyclo:
      min-complexity: 15
    misspell:
      locale: US
    revive:
      rules:
        - name: exported
          severity: warning
        - name: unexported-return
          severity: warning
        - name: error-return
          severity: error
        - name: error-naming
          severity: error
        - name: var-naming
          severity: warning
        - name: if-return
          severity: warning
        - name: increment-decrement
          severity: warning
        - name: var-declaration
          severity: warning
        - name: range
          severity: warning
        - name: range-val-in-closure
          severity: warning
        - name: range-val-address
          severity: error
        - name: waitgroup-by-value
          severity: error
        - name: atomic
          severity: error
        - name: empty-block
          severity: warning
        - name: superfluous-else
          severity: warning
        - name: unused-parameter
          severity: warning
        - name: unreachable-code
          severity: error
        - name: redefines-builtin-id
          severity: warning
  exclusions:
    rules:
      - path: _test\.go
        linters:
          - errcheck
          - gocritic

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
