apiVersion: neuvector.com/v1
kind: NvSecurityRule
metadata:
    name: nv.bookstore-ui.publishing-company
    namespace: publishing-company
spec:
    dlp:
        settings:
            - action: deny
              name: sensor.creditcard
        status: true
    egress:
        - action: allow
          applications:
            - Consul
            - SSL
          name: nv.consul-server.consul-egress-0
          ports: any
          selector:
            comment: ""
            name: nv.consul-server.consul
            name_referral: true
            original_name: ""
    file: []
    # many rules
    ingress: []
    process:
        - action: allow
          allow_update: false
          name: consul-dataplane
          path: /usr/local/bin/consul-dataplane
        - action: allow
          allow_update: false
          name: nginx
          path: /usr/sbin/nginx
    target:
        policymode: Monitor
        selector:
            name: nv.bookstore-ui.publishing-company
