apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    labels:
        app: postgres
    name: data-pvc
    namespace: default
spec:
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            storage: 10Gi
    storageClassName: standard
    volumeMode: Filesystem
