apiVersion: v1
data:
    # this is the Cache Time To Live
    #
    # one our is our default value
    CACHE_TTL: "3600"
    # Database host FQDN
    #
    # this is only the FQDN of the host
    #   port 5432 is assumed by default, if not specified otherwise
    DB_HOST: "postgres.default.svc.cluster.local"
    FEATURE_FLAGS: "new-ui,beta-api"
    # this is the app specific log level
    #   possible values are "info", "debug" and "none"
    #   you may need to restart the app for the change to take effect
    LOG_LEVEL: "info"
kind: ConfigMap
metadata:
    labels:
        app: myapp
    name: app-config
    namespace: default
